### ISSUE TITLE
C# dashboard mechanism outputting html too late

### ISSUE THREAD

**Issue by diddledan** [iolevel/wpdotnet-sdk#9] opened 2018-10-10 11:35 UTC
I've downloaded the example implementation from https://github.com/iolevel/peachpie-wordpress and spun up an unmodified test. Looking at the dashboard it seems that the HTML output by the razor code is arriving too late, and is corrupt. The dashboard widget is supposed to be entirely in the first column, but the razor content is spanning both first and second columns. The `<h2>` tag begins in the first column, the column is closed, and then the `<h2>` is closed in the second column. Is this an asynchronous bug?

The HTML output is:

```html
<div id="postbox-container-1" class="postbox-container">
    <!-- other first-column widgets removed for brevity -->

<div id="peachpied.widget.1" class="postbox " >
<button type="button" class="handlediv" aria-expanded="true"><span class="screen-reader-text">Toggle panel: Razor Partial View</span><span class="toggle-indicator" aria-hidden="true"></span></button><h2 class='hndle'><span>Razor Partial View</span></h2>
<div class="inside">
</div>

<h2>Hello from Partial View </div>
</div>	</div>
	<div id="postbox-container-2" class="postbox-container">
	Dashboard Widget</h2>
<p>This widget is rendered directly from Razor Partial View! See me in /Views/Shared/DashboardWidget.cshtml</p>

    <!-- other second-column widgets removed for brevity -->
```

This results in the following corruption:

![image](https://user-images.githubusercontent.com/147548/46733318-d8844b00-cc87-11e8-889f-4bbb3572b625.png)

**Comment by jakubmisek** [comment] 2018-10-16 19:27
Thanks! This is caused by `peachpie-wordpress` demo itself. It rendered the partial view asynchronously by mistake. fixed in https://github.com/iolevel/peachpie-wordpress/commit/a12d1c6a898d75ac8a0db90c5b05af5a616e9943

**Closed by jakubmisek** 2018-10-16 19:27 UTC
