### ISSUE TITLE
Edit with elementor not loading elementor editor

### ISSUE THREAD

**Issue by JackMutobu** [iolevel/wpdotnet-sdk#90] opened 2020-10-08 12:15 UTC
**Describe the bug**
When trying to edit a page with elementor, elementor plugin's editor is not loaded
![Annotation 2020-10-08 145959](https://user-images.githubusercontent.com/33978327/95456332-d6891b80-0977-11eb-8685-2790357719eb.png)
And enabling safe mode is failing causing this message
![Annotation 2020-10-08 150039](https://user-images.githubusercontent.com/33978327/95456402-f0c2f980-0977-11eb-8c0b-55c5bbc0e7cf.png)

**To Reproduce**

- Install Elementor 3.0.11-preview2 plugin 
- Activate the plugin in wordpress dashboard
- Create a new page
-Try click Edit with elementor 
![image](https://user-images.githubusercontent.com/33978327/95456613-47303800-0978-11eb-9c21-ef75aaa7de3a.png)

**Expected behavior**
Elementor editor should be loaded 

**Screenshots**

**System information:**
 - OS: Windows 10 Enterprise
 - Version : 19042.546

**Stack trace:**

**Additional context**

PeachPied.WordPress.AspNetCore version:5.5.1-preview2
elementor version:3.0.11-preview2

**Comment by roberthusak** [comment] 2020-10-17 13:03
Fixed in PeachPie by https://github.com/peachpiecompiler/peachpie/commit/efe31569bd54db6617caa611ca9bcd16d7abce61, it should work once we release the next PeachPie version. @jakubmisek

**Comment by roberthusak** [comment] 2020-10-17 18:25
Another error with using the Elementor GUI is caused by https://github.com/peachpiecompiler/peachpie/issues/868. It should work once fixed.

**Comment by JackMutobu** [comment] 2020-10-17 18:29
Is it possible to have a temporary workaround?

**Comment by roberthusak** [comment] 2020-10-21 08:58
Try it now with the latest `5.5.1-preview3` version of WpDotNet (don't forget to update the plugins to `X.X.X-preview3` versions as well). Please let us know if there are still any problems so that we can close this issue if possible.

**Comment by JackMutobu** [comment] 2020-10-21 09:57
I have just updated to latest previews, it is loading very well now. Thanks for resolving this issue.

**Comment by roberthusak** [comment] 2020-10-22 07:11
Glad to hear that, thanks for reporting it in the first place.

**Closed by roberthusak** 2020-10-22 07:11 UTC
Labels: bug
