### ISSUE TITLE
Cannot use with SMTP mail sender

### ISSUE THREAD

**Issue by hez2010** [iolevel/wpdotnet-sdk#70] opened 2020-03-21 13:20 UTC
**Describe the bug**
SMTP in PHP requires `stream_socket_enable_crypto` and other functions that currently peachpie doesn't support.

**To Reproduce**
Compile `wp-smtp` plugin and try send email with it.

**Expected behavior**
Email sent successfully.

**System information:**
 - OS: Windows 10 2004, Ubuntu 18.04
 - Version 1.0.0-beta910

**Stack trace:**
```
Error: Call to undefined function stream_socket_enable_crypto()
Stack trace:
#0 : SMTP->startTLS()
#1 : PHPMailer->smtpConnect($options)
#2 : PHPMailer->smtpSend($header, $body)
#3 : PHPMailer->postSend()
#4 : PHPMailer->send()
#5 : {main}
#6 : WP_SMTP->wp_smtp_page()
#7 : WP_Hook->apply_filters($value, $args)
#8 : WP_Hook->do_action($args)
#9 : do_action($tag, $arg)
#10 : {main}
#11 : {main}
#12 : RewriteMiddleware->Invoke($context)
#13 : <Invoke>d__16->MoveNext()
#14 : WpResponseCacheMiddleware->Invoke($context)
#15 : StaticFileMiddleware->Invoke($context)
#16 : DefaultFilesMiddleware->Invoke($context)
#17 : <Invoke>d__9->MoveNext()
#18 : DeveloperExceptionPageMiddleware->Invoke($context)
#19 : <Invoke>d__3->MoveNext()
#20 : ResponseCompressionMiddleware->Invoke($context)
#21 : HttpsRedirectionMiddleware->Invoke($context)
#22 : HostFilteringMiddleware->Invoke($context)
#23 : HostingApplication->ProcessRequestAsync($context)
#24 : <ProcessRequests>d__217`1->MoveNext()
#25 : HttpProtocol->ProcessRequests($application)
#26 : <ProcessRequestsAsync>d__216`1->MoveNext()
#27 : HttpProtocol->ProcessRequestsAsync($application)
#28 : Http2Stream`1->Execute()
```

**Additional context**
A compiled `wp-smtp` plugin: 
[wp-smtp.1.1.10-beta.zip](https://github.com/iolevel/wpdotnet-sdk/files/4362937/wp-smtp.1.1.10-beta.zip)

**Comment by jakubmisek** [comment] 2020-04-21 13:08
thank you @hez2010 for the sample project. You are right, the function `stream_socket_enable_crypto` is not defined and causes the error above (inside `PHPMailer`).

We'll try to enable PHPMailer in future updates.

**Comment by jakubmisek** [comment] 2020-04-24 19:31
implemented in https://github.com/peachpiecompiler/peachpie/commit/9b752e511a37a76a6f63c05ae61ace5cf811de7c

will be available once wpdotnet will be updated to latest peachpie (>`0.9.961`)

**Comment by hez2010** [comment] 2020-04-25 10:34
Thanks

**Comment by hez2010** [comment] 2020-04-28 06:21
Hello, I occurred a new error while using SMTP:
```
SMTP ERROR: Failed to connect to server: The handshake failed due to an unexpected packet format. (-1)SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
```

Maybe there're some issues with socket/smtp client implementation?

**Comment by jakubmisek** [comment] 2020-04-28 22:13
it is possible, `stream_socket_enable_crypto` has been implemented, so now it can be something else :)

We have tested SMTP for our mail provider on TLS and it worked.

Do you know where in the code it reports `SMTP ERROR`?
Can you tell what is the email provider you're using?

**Comment by hez2010** [comment] 2020-04-29 07:32
I use SMTP with plugin Easy WP SMTP. And my SMTP provider is Mailjet(https://www.mailjet.com/).

**Comment by hez2010** [comment] 2020-04-29 16:12
This is a full log generated by plugin "Configure SMTP":
```
2020-04-29 16:09:44 Connection: opening to in-v3.mailjet.com:587, timeout=300, options=array ()
2020-04-29 16:09:45 Connection: opened
2020-04-29 16:09:45 SMTP -> get_lines(): $data is ""
2020-04-29 16:09:45 SMTP -> get_lines(): $str is "220 in.mailjet.com ESMTP Mailjet"
2020-04-29 16:09:45 SERVER -> CLIENT: 220 in.mailjet.com ESMTP Mailjet
2020-04-29 16:09:45 CLIENT -> SERVER: EHLO hez2010.com
2020-04-29 16:09:45 SMTP -> get_lines(): $data is ""
2020-04-29 16:09:45 SMTP -> get_lines(): $str is "250-smtpin.mailjet.com"
2020-04-29 16:09:45 SMTP -> get_lines(): $data is "250-smtpin.mailjet.com"
2020-04-29 16:09:45 SMTP -> get_lines(): $str is "250-PIPELINING"
2020-04-29 16:09:45 SMTP -> get_lines(): $data is "250-smtpin.mailjet.com250-PIPELINING"
2020-04-29 16:09:45 SMTP -> get_lines(): $str is "250-SIZE 15728640"
2020-04-29 16:09:45 SMTP -> get_lines(): $data is "250-smtpin.mailjet.com250-PIPELINING250-SIZE 15728640"
2020-04-29 16:09:45 SMTP -> get_lines(): $str is "250-VRFY"
2020-04-29 16:09:45 SMTP -> get_lines(): $data is "250-smtpin.mailjet.com250-PIPELINING250-SIZE 15728640250-VRFY"
2020-04-29 16:09:45 SMTP -> get_lines(): $str is "250-ETRN"
2020-04-29 16:09:45 SMTP -> get_lines(): $data is "250-smtpin.mailjet.com250-PIPELINING250-SIZE 15728640250-VRFY250-ETRN"
2020-04-29 16:09:45 SMTP -> get_lines(): $str is "250-STARTTLS"
2020-04-29 16:09:45 SMTP -> get_lines(): $data is "250-smtpin.mailjet.com250-PIPELINING250-SIZE 15728640250-VRFY250-ETRN250-STARTTLS"
2020-04-29 16:09:45 SMTP -> get_lines(): $str is "250-AUTH PLAIN LOGIN DIGEST-MD5 CRAM-MD5"
2020-04-29 16:09:45 SMTP -> get_lines(): $data is "250-smtpin.mailjet.com250-PIPELINING250-SIZE 15728640250-VRFY250-ETRN250-STARTTLS250-AUTH PLAIN LOGIN DIGEST-MD5 CRAM-MD5"
2020-04-29 16:09:45 SMTP -> get_lines(): $str is "250-AUTH=PLAIN LOGIN DIGEST-MD5 CRAM-MD5"
2020-04-29 16:09:45 SMTP -> get_lines(): $data is "250-smtpin.mailjet.com250-PIPELINING250-SIZE 15728640250-VRFY250-ETRN250-STARTTLS250-AUTH PLAIN LOGIN DIGEST-MD5 CRAM-MD5250-AUTH=PLAIN LOGIN DIGEST-MD5 CRAM-MD5"
2020-04-29 16:09:45 SMTP -> get_lines(): $str is "250-ENHANCEDSTATUSCODES"
2020-04-29 16:09:45 SMTP -> get_lines(): $data is "250-smtpin.mailjet.com250-PIPELINING250-SIZE 15728640250-VRFY250-ETRN250-STARTTLS250-AUTH PLAIN LOGIN DIGEST-MD5 CRAM-MD5250-AUTH=PLAIN LOGIN DIGEST-MD5 CRAM-MD5250-ENHANCEDSTATUSCODES"
2020-04-29 16:09:45 SMTP -> get_lines(): $str is "250-8BITMIME"
2020-04-29 16:09:45 SMTP -> get_lines(): $data is "250-smtpin.mailjet.com250-PIPELINING250-SIZE 15728640250-VRFY250-ETRN250-STARTTLS250-AUTH PLAIN LOGIN DIGEST-MD5 CRAM-MD5250-AUTH=PLAIN LOGIN DIGEST-MD5 CRAM-MD5250-ENHANCEDSTATUSCODES250-8BITMIME"
2020-04-29 16:09:45 SMTP -> get_lines(): $str is "250 SMTPUTF8"
2020-04-29 16:09:45 SERVER -> CLIENT: 250-smtpin.mailjet.com250-PIPELINING250-SIZE 15728640250-VRFY250-ETRN250-STARTTLS250-AUTH PLAIN LOGIN DIGEST-MD5 CRAM-MD5250-AUTH=PLAIN LOGIN DIGEST-MD5 CRAM-MD5250-ENHANCEDSTATUSCODES250-8BITMIME250 SMTPUTF8
2020-04-29 16:09:45 CLIENT -> SERVER: STARTTLS
2020-04-29 16:09:46 SMTP -> get_lines(): $data is ""
2020-04-29 16:09:46 SMTP -> get_lines(): $str is "220 2.0.0 Ready to start TLS"
2020-04-29 16:09:46 SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
SMTP Error: Could not connect to SMTP host.
2020-04-29 16:09:46 CLIENT -> SERVER: QUIT
2020-04-29 16:09:46 SMTP -> get_lines(): $data is ""
2020-04-29 16:09:46 SMTP -> get_lines(): $str is "}dZ(��H���q��3J�0���$�"
2020-04-29 16:09:46 SERVER -> CLIENT: }dZ(��H���q��3J�0���$�
2020-04-29 16:09:46 SMTP ERROR: QUIT command failed: }dZ(��H���q��3J�0���$�
2020-04-29 16:09:46 Connection: closed
SMTP Error: Could not connect to SMTP host.
```

**Comment by jakubmisek** [comment] 2020-05-01 12:23
thanks!

**Comment by jakubmisek** [comment] 2020-05-02 11:27
seems it is caused by bug in `base64_decode` (https://github.com/peachpiecompiler/peachpie/issues/739)
Will be fixed!

**Comment by jakubmisek** [comment] 2020-05-11 21:44
beta980 fixes the issue, please let me know if it still fails

**Comment by hez2010** [comment] 2020-05-12 03:51
Hi, I've tested but SMTP only work with SSL(465) but not TLS(576).

**Comment by jakubmisek** [comment] 2020-05-12 08:46
thanks, the same log? TLS worked for us.

**Comment by hez2010** [comment] 2020-05-12 11:10
Log:
```
2020-05-12 11:08:08 Connection: opening to in-v3.mailjet.com:587, timeout=300, options=array ()
2020-05-12 11:08:09 Connection: opened
2020-05-12 11:08:10 SMTP -> get_lines(): $data is ""
2020-05-12 11:08:10 SMTP -> get_lines(): $str is "220 in.mailjet.com ESMTP Mailjet"
2020-05-12 11:08:10 SERVER -> CLIENT: 220 in.mailjet.com ESMTP Mailjet
2020-05-12 11:08:10 CLIENT -> SERVER: EHLO hez2010.com
2020-05-12 11:08:10 SMTP -> get_lines(): $data is ""
2020-05-12 11:08:10 SMTP -> get_lines(): $str is "250-smtpin.mailjet.com"
2020-05-12 11:08:10 SMTP -> get_lines(): $data is "250-smtpin.mailjet.com"
2020-05-12 11:08:10 SMTP -> get_lines(): $str is "250-PIPELINING"
2020-05-12 11:08:10 SMTP -> get_lines(): $data is "250-smtpin.mailjet.com250-PIPELINING"
2020-05-12 11:08:10 SMTP -> get_lines(): $str is "250-SIZE 15728640"
2020-05-12 11:08:10 SMTP -> get_lines(): $data is "250-smtpin.mailjet.com250-PIPELINING250-SIZE 15728640"
2020-05-12 11:08:10 SMTP -> get_lines(): $str is "250-VRFY"
2020-05-12 11:08:10 SMTP -> get_lines(): $data is "250-smtpin.mailjet.com250-PIPELINING250-SIZE 15728640250-VRFY"
2020-05-12 11:08:10 SMTP -> get_lines(): $str is "250-ETRN"
2020-05-12 11:08:10 SMTP -> get_lines(): $data is "250-smtpin.mailjet.com250-PIPELINING250-SIZE 15728640250-VRFY250-ETRN"
2020-05-12 11:08:10 SMTP -> get_lines(): $str is "250-STARTTLS"
2020-05-12 11:08:10 SMTP -> get_lines(): $data is "250-smtpin.mailjet.com250-PIPELINING250-SIZE 15728640250-VRFY250-ETRN250-STARTTLS"
2020-05-12 11:08:10 SMTP -> get_lines(): $str is "250-AUTH PLAIN LOGIN DIGEST-MD5 CRAM-MD5"
2020-05-12 11:08:10 SMTP -> get_lines(): $data is "250-smtpin.mailjet.com250-PIPELINING250-SIZE 15728640250-VRFY250-ETRN250-STARTTLS250-AUTH PLAIN LOGIN DIGEST-MD5 CRAM-MD5"
2020-05-12 11:08:10 SMTP -> get_lines(): $str is "250-AUTH=PLAIN LOGIN DIGEST-MD5 CRAM-MD5"
2020-05-12 11:08:10 SMTP -> get_lines(): $data is "250-smtpin.mailjet.com250-PIPELINING250-SIZE 15728640250-VRFY250-ETRN250-STARTTLS250-AUTH PLAIN LOGIN DIGEST-MD5 CRAM-MD5250-AUTH=PLAIN LOGIN DIGEST-MD5 CRAM-MD5"
2020-05-12 11:08:10 SMTP -> get_lines(): $str is "250-ENHANCEDSTATUSCODES"
2020-05-12 11:08:10 SMTP -> get_lines(): $data is "250-smtpin.mailjet.com250-PIPELINING250-SIZE 15728640250-VRFY250-ETRN250-STARTTLS250-AUTH PLAIN LOGIN DIGEST-MD5 CRAM-MD5250-AUTH=PLAIN LOGIN DIGEST-MD5 CRAM-MD5250-ENHANCEDSTATUSCODES"
2020-05-12 11:08:10 SMTP -> get_lines(): $str is "250-8BITMIME"
2020-05-12 11:08:10 SMTP -> get_lines(): $data is "250-smtpin.mailjet.com250-PIPELINING250-SIZE 15728640250-VRFY250-ETRN250-STARTTLS250-AUTH PLAIN LOGIN DIGEST-MD5 CRAM-MD5250-AUTH=PLAIN LOGIN DIGEST-MD5 CRAM-MD5250-ENHANCEDSTATUSCODES250-8BITMIME"
2020-05-12 11:08:10 SMTP -> get_lines(): $str is "250 SMTPUTF8"
2020-05-12 11:08:10 SERVER -> CLIENT: 250-smtpin.mailjet.com250-PIPELINING250-SIZE 15728640250-VRFY250-ETRN250-STARTTLS250-AUTH PLAIN LOGIN DIGEST-MD5 CRAM-MD5250-AUTH=PLAIN LOGIN DIGEST-MD5 CRAM-MD5250-ENHANCEDSTATUSCODES250-8BITMIME250 SMTPUTF8
2020-05-12 11:08:10 CLIENT -> SERVER: STARTTLS
2020-05-12 11:08:10 SMTP -> get_lines(): $data is ""
2020-05-12 11:08:10 SMTP -> get_lines(): $str is "220 2.0.0 Ready to start TLS"
2020-05-12 11:08:10 SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
SMTP Error: Could not connect to SMTP host.
2020-05-12 11:08:11 CLIENT -> SERVER: QUIT
2020-05-12 11:08:11 SMTP -> get_lines(): $data is ""
2020-05-12 11:08:11 SMTP -> get_lines(): $str is ""{M��_�}�#CsG/bbO%�����"
2020-05-12 11:08:11 SERVER -> CLIENT: "{M��_�}�#CsG/bbO%�����
2020-05-12 11:08:11 SMTP ERROR: QUIT command failed: "{M��_�}�#CsG/bbO%�����
2020-05-12 11:08:11 Connection: closed
SMTP Error: Could not connect to SMTP host.
```

**Comment by jakubmisek** [comment] 2020-05-15 14:36
I have tried mailjet a few more times with TLS and it works just fine. Are you sure you have updated dependencies to PeachPie to the latest version 0.9.981?

**Comment by hez2010** [comment] 2020-05-16 02:59
> Are you sure you have updated dependencies to PeachPie to the latest version 0.9.981?

Yes, and my csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PeachPied.WordPress.AspNetCore" Version="1.0.0-beta980" />
  </ItemGroup>

</Project>
```

> I have tried mailjet a few more times with TLS and it works just fine.

That's weird, I can only send email through port 465 with SSL, but not 576 with TLS....
I'll try again later with the next upcoming release of PeachPie.

**Comment by hez2010** [comment] 2020-10-10 15:55
Hi, after upgrade to 5.5.1-preview2 from 1.0.0-beta980, SMTP stop working again.
I'm using plugin WP-SMTP, and SMTP Provider is Mailjet, configured to send email via port 465.
```
SMTP Error: Could not authenticate.
```

**Comment by jakubmisek** [comment] 2020-10-15 13:30
thank you @hez2010 , it was an issue with socket_select() and SSL streams
fixed in https://github.com/peachpiecompiler/peachpie/commit/f6ccc67db759ee434a6316f223b0408515f777c7

**Closed** 2020-10-15 13:30 UTC
Labels: bug
