### ISSUE TITLE
http://wpdotnet.com/ is not working

### ISSUE THREAD

**Issue by gautamkrishnar** [iolevel/wpdotnet-sdk#35] opened 2019-06-10 17:38 UTC
**Describe the bug**
http://wpdotnet.com/ is not working

**To Reproduce**
Visit http://wpdotnet.com/

**Expected behavior**
Site should be shown

**Additional context**
Please add redirect to www when visiting http://wpdotnet.com/

**Comment by bfistein** [comment] 2019-06-10 17:44
Thank you @gautamkrishnar, we are aware of this issue, which is caused by a slight misconfiguration of the ASP.NET Core response cache. Will be fixed soon with a new release of WpDotNet.

**Comment by jakubmisek** [comment] 2019-06-15 11:57
fixed, we have kept some apsnetcore 2.0 DLLs in the folder together with 2.2 ..

**Closed by jakubmisek** 2019-06-15 11:57 UTC
Labels: bug

**Comment by gautamkrishnar** [comment] 2019-06-15 12:00
👍
