### ISSUE TITLE
Resources not installed in Rider

### ISSUE THREAD

**Issue by TobiasMorell** [iolevel/wpdotnet-sdk#19] opened 2019-02-11 15:48 UTC
**Describe the bug**
None of the resources are added under the wordpress folder when installing the package from Rider. 

**To Reproduce**

1. Open Rider
2. Create new 'Web API'
3. Open .csproj in text editor and add `<PackageReference include="Peachpied.WordPress.AspNetCore" Version="1.0.0-alpha6" />` and wait for it to complete
4. Run the solution and open up `localhost:5000`, a page shows up, but there is no styling.

After inspecting the folder in my filesystem or using ls, no files show up. It seems they only exist in Rider.

**Expected behavior**
I had expected the files to actually be installed on my system.

**System information:**
 - OS: Ubuntu
 - Version 18.04

**Possible workaround:**
Clone or download the repo as a zip and copy the files under the *wordpress* folder into the seemingly empty *wordpress* folder in your project.

**Comment by jakubmisek** [comment] 2019-02-12 11:53
thank you, please check the files are not even in the `bin` folder (`bin/debug/netcoreapp2.1/wordpress`).

**Comment by bfistein** [comment] 2019-03-01 16:06
@TobiasMorell any updates please? Did you find the files in the `bin` folder or should we investigate more?

**Comment by TobiasMorell** [comment] 2019-03-03 18:53
Sorry for the wait. I just checked and can confirm that the WordPress files are in `bin/debug/netcoreapp2.1/wordpress`. They are not located in the root of the project, as expected.

I tried to delete the whole `wordpress` folder outside Rider. After running an exception occurs, stating that the files do not exist (which makes sense), but they are still listed in the directory in Rider. I have attached a screenshot.

![image](https://user-images.githubusercontent.com/9692119/53699946-a10c6b80-3ded-11e9-9f70-2d153ba70971.png)

**Comment by jakubmisek** [comment] 2019-03-05 15:40
The files should not be copied into your project's root (a NuGet dependency does not modify your project content), so this behavior is correct and expected.

Content files are copied to your build folder upon build/publish. In case of Visual Studio, it shows you a shortcut in your project root to the content files but they actually don't exist.

The exception on screenshot is caused by invalid path passed to `.UseWordpress( path: <this must be correct path> )`. This parameter was omitted but very important. This is fixed in recent updates where if you don't the path, we pick the correct one automatically.

**Closed by jakubmisek** 2019-03-05 15:40 UTC
Labels: bug
